services:
  postgres:
    image: postgres:latest
    container_name: bewear-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: bewear-db
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: