import './globals.css'

import type { Metadata } from 'next'
import { Geist, Geist_Mono, Poppins } from 'next/font/google'

import { Footer } from '@/components/common/footer'
import { Header } from '@/components/common/header'
import { Toaster } from '@/components/ui/sonner'
import { ItemsCartProvider } from '@/providers/ItemsCart'
import { ProductVariantProvider } from '@/providers/ProductVariant'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} flex min-h-screen flex-col font-[Poppins] antialiased`}
      >
        <ProductVariantProvider>
          <ItemsCartProvider>
            <Header />
            <div className="flex-1">{children}</div>
          </ItemsCartProvider>
        </ProductVariantProvider>
        <Footer />
        <Toaster richColors />
      </body>
    </html>
  )
}
